### PR TITLE
feat: Integration with Blockscout explorer

### PR DESCRIPTION
**Pull request by tom2drum**
- added initial integration with Blockscout explorer
- supported features
  - transaction explanation
  - main address label
  - phalcon explorer link

### CODE REVIEW

**Comment by cong1223** [comment]
Thank you for your pull request. Additionally, can you confirm the availability of the waitUntilDataLoaded function? When I run the plugin, I am never able to access the element with the ID meta-suites__tx-info-label, which is preventing the new feature you provided from working.

**Comment by cong1223** [comment]
image

**Comment by tom2drum** [comment]
> Additionally, can you confirm the availability of the waitUntilDataLoaded function? 

This function is essential to verify if the main page content has loaded and the UI is ready to show MetaSuites extension elements.

> When I run the plugin, I am never able to access the element with the ID meta-suites__tx-info-label, which is preventing the new feature you provided from working.

Yeah. We haven't released the integration code on our end yet. Even if you have the extension installed, you won't see any changes on the Blockscout pages.

**Comment by cong1223** [comment]
> > Additionally, can you confirm the availability of the waitUntilDataLoaded function?
> 
> This function is essential to verify if the main page content has loaded and the UI is ready to show MetaSuites extension elements.
> 
> > When I run the plugin, I am never able to access the element with the ID meta-suites__tx-info-label, which is preventing the new feature you provided from working.
> 
> Yeah. We haven't released the integration code on our end yet. Even if you have the extension installed, you won't see any changes on the Blockscout pages.

Is there any possibility for our team members to test these newly added codes locally?

**Comment by tom2drum** [comment]
@cong1223 we've released changes on our side. Now you can see an example of the integration here - https://eth.blockscout.com

**Comment by cong1223** [comment]
> @cong1223 we've released changes on our side. Now you can see an example of the integration here - https://eth.blockscout.com

OK, i will review the code tomorrow.

**Pull request merged**
